import React from 'react';
import { Utensils, ShoppingBag, PieChart, Settings, Package, X, Plus, Minus, Search, Trash2, Send, History, LayoutDashboard, ClipboardList, Download, Upload, ShieldCheck, Lock, Mic, QrCode, User, Users, CheckCircle, ChevronDown, ChevronRight, Play, Pause, Check, CreditCard, Image, Loader2, LogOut, Truck, ChefHat, Edit, Menu, Info, PlusCircle, Inbox, Printer, FileText, Smartphone, Monitor, Zap, Percent, Bell, RefreshCw } from 'lucide-react';

export const HEADING_CLICKS_REQUIRED = 7;

export const ICONS = {
  Utensils: <Utensils size={20} />,
  ShoppingBag: <ShoppingBag size={20} />,
  PieChart: <PieChart size={20} />,
  Settings: <Settings size={20} />,
  Package: <Package size={20} />,
  X: <X size={20} />,
  Plus: <Plus size={20} />,
  Minus: <Minus size={20} />,
  Search: <Search size={20} />,
  Trash2: <Trash2 size={20} />,
  Send: <Send size={20} />,
  History: <History size={20} />,
  Dashboard: <LayoutDashboard size={20} />,
  Inventory: <ClipboardList size={20} />,
  Download: <Download size={20} />,
  Upload: <Upload size={20} />,
  Shield: <ShieldCheck size={20} />,
  Lock: <Lock size={16} />,
  LogOut: <LogOut size={20} />,
  Mic: <Mic size={16} />,
  QrCode: <QrCode size={20} />,
  User: <User size={20} />,
  Users: <Users size={20} />,
  CheckCircle: <CheckCircle size={20} />,
  ChevronDown: <ChevronDown size={20} />,
  ChevronRight: <ChevronRight size={20} />,
  Play: <Play size={16} />,
  Pause: <Pause size={16} />,
  Check: <Check size={20} />,
  CreditCard: <CreditCard size={20} />,
  Image: <Image size={20} />,
  Loader: <Loader2 size={20} className="animate-spin" />,
  Truck: <Truck size={20} />,
  ChefHat: <ChefHat size={20} />,
  Edit: <Edit size={20} />,
  Menu: <Menu size={20} />,
  Info: <Info size={20} />,
  PlusCircle: <PlusCircle size={20} />,
  Inbox: <Inbox size={20} />,
  Printer: <Printer size={20} />,
  FileText: <FileText size={20} />,
  Smartphone: <Smartphone size={20} />,
  Monitor: <Monitor size={20} />,
  Zap: <Zap size={20} />,
  Percent: <Percent size={20} />,
  Bell: <Bell size={20} />,
  Refresh: <RefreshCw size={20} />,
};

export const CATEGORIES = ["BBQ", "Drinks", "Karahi", "Raita"];

export const INITIAL_ITEMS = [];

export const PRINT_TRANSLATIONS = {
  english: {
    invoice: 'INVOICE',
    orderNo: 'ORDER NO',
    billNo: 'BILL NO',
    date: 'DATE',
    time: 'TIME',
    customer: 'CUSTOMER',
    phone: 'PHONE',
    table: 'TABLE',
    pay: 'PAY',
    itemDescription: 'ITEM DESCRIPTION',
    amount: 'AMOUNT',
    notes: 'NOTES',
    subtotal: 'SUBTOTAL',
    tax: 'TAX',
    discount: 'DISCOUNT',
    total: 'TOTAL',
    thankYou: 'THANK YOU FOR YOUR VISIT!',
    softwareBy: 'Software by: Smart Order Taker',
    kitchen: 'KITCHEN',
    bill: 'BILL'
  },
  urdu: {
    invoice: 'بل',
    orderNo: 'آرڈر نمبر',
    billNo: 'بل نمبر',
    date: 'تاریخ',
    time: 'وقت',
    customer: 'کسٹمر',
    phone: 'فون',
    table: 'میز',
    pay: 'ادائیگی',
    itemDescription: 'آئٹم کی تفصیل',
    amount: 'رقم',
    notes: 'نوٹس',
    subtotal: 'ذیلی کل',
    tax: 'ٹیکس',
    discount: 'ڈسکاؤنٹ',
    total: 'کل',
    thankYou: 'آپ کے دورے کا شکریہ!',
    softwareBy: 'سافٹ ویئر: اسمارٹ آرڈر ٹیکر',
    kitchen: 'کیچن',
    bill: 'بل'
  }
};
