import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Order, OrderStatus, StaffMember, AppSettings } from '../types';
import { ICONS } from '../constants';
import TimeElapsed from './TimeElapsed';

interface LiveOrdersViewProps {
  orders: Order[];
  onUpdateStatus: (order: Order, status: OrderStatus) => void;
  onEditOrder: (order: Order) => void;
  activeStaff: StaffMember | null;
  settings: AppSettings;
  notify: (message: string, type?: 'success' | 'error' | 'info') => void;
  triggerConfirm: (config: { title: string; message: string; onConfirm: () => void; type?: 'danger' | 'info' }) => void;
  isAdmin?: boolean;
  onUpdateOrder: (order: Order) => void;
}

const LiveOrdersView: React.FC<LiveOrdersViewProps> = ({ 
  orders, onUpdateStatus, onEditOrder, activeStaff, settings, notify, triggerConfirm, isAdmin, onUpdateOrder 
}) => {
  const [filterStatus, setFilterStatus] = useState<OrderStatus | 'all'>('all');
  const [showSummary, setShowSummary] = useState(false);
  const [viewMode, setViewMode] = useState<'active' | 'print'>('active');

  const handlePrintOrder = (order: Order) => {
    try {
      if (settings.enableKitchenPrinting === false) {
        notify("Kitchen Printing is disabled in Settings!", "error");
        return;
      }
      const printSection = document.getElementById('print-section');
      if (!printSection) throw new Error("Print section not found");

      const headerName = settings.businessName;
      const itemsHtml = order.items.map(item => `
        <div style="display: flex; justify-content: space-between; border-bottom: 1px dashed #ccc; padding: 6px 0; font-size: 12px; font-family: 'Courier New', Courier, monospace;">
          <div style="flex: 1; text-align: left; padding-right: 10px;">
            <div style="font-weight: bold;">${item.name.toUpperCase()}</div>
            <div style="font-size: 10px; color: #333;">
              ${item.unit === 'rs' ? `Rs. ${item.quantity}` : `${item.quantity} x Rs. ${item.price}`}
            </div>
          </div>
          <div style="width: 70px; text-align: right; font-weight: bold; align-self: center;">
            Rs.${(item.price * item.quantity).toFixed(0)}
          </div>
        </div>
      `).join('');

      printSection.innerHTML = `
        <div style="font-family: 'Courier New', Courier, monospace; color: black; background: white; width: 100%; box-sizing: border-box; padding: 0;">
          <div style="text-align: center; margin-bottom: 15px;">
            <h1 style="margin: 0; font-size: 22px; text-transform: uppercase; font-weight: 900;">${headerName}</h1>
            <p style="margin: 2px 0; font-size: 10px; letter-spacing: 3px; font-weight: bold;">*** KITCHEN ORDER ***</p>
          </div>
          
          <div style="border-top: 2px solid #000; border-bottom: 2px solid #000; padding: 8px 0; margin-bottom: 10px; font-size: 11px; line-height: 1.5;">
            <div style="display: flex; justify-content: space-between;">
              <span><b>ORDER ID:</b> ${order.id.slice(-8).toUpperCase()}</span>
              <span><b>DATE:</b> ${new Date(order.timestamp).toLocaleString()}</span>
            </div>
            <div style="margin-top: 4px;">
              <b>CUSTOMER:</b> ${order.customerName.toUpperCase()}
            </div>
            <div style="display: flex; justify-content: space-between; margin-top: 4px;">
              ${order.tableNumber ? `<span><b>TABLE:</b> ${order.tableNumber.toUpperCase()}</span>` : '<span></span>'}
              <span><b>NO:</b> #${order.orderNumber || '??'}</span>
            </div>
          </div>
          
          <div style="margin-bottom: 15px;">
            <div style="display: flex; justify-content: space-between; font-weight: bold; font-size: 10px; border-bottom: 1px solid #000; padding-bottom: 4px; margin-bottom: 4px;">
              <span>ITEM DESCRIPTION</span>
              <span>QTY</span>
            </div>
            ${itemsHtml}
          </div>

          ${order.kitchenNotes ? `
            <div style="border: 1px solid #000; padding: 8px; margin-top: 10px; font-size: 12px;">
              <b>NOTES:</b> ${order.kitchenNotes.toUpperCase()}
            </div>
          ` : ''}
          
          <div style="text-align: center; margin-top: 25px; border-top: 1px dashed #000; padding-top: 15px;">
            <p style="margin: 0; font-size: 9px; color: #666;">Generated by: Smart Order Taker</p>
          </div>
        </div>
      `;
      printSection.style.display = 'block';
      window.print();
      printSection.style.display = 'none';

      // Update printed status
      onUpdateOrder({ ...order, isPrinted: true });
      notify("Order Printed", "success");
    } catch (e) {
      notify("Printing Error: " + (e as Error).message, "error");
    }
  };

  const activeOrders = orders
    .filter(o => {
      const kitchenStatuses = ['received', 'preparing', 'ready'];
      const takerStatuses = ['received', 'preparing', 'ready'];
      const allowedStatuses = activeStaff?.role === 'kitchen' ? kitchenStatuses : takerStatuses;

      // Filter by status
      const statusMatch = filterStatus === 'all' 
        ? (o.status && allowedStatuses.includes(o.status))
        : o.status === filterStatus;

      if (!statusMatch) return false;

      // If staff is a taker, only show their own orders
      if (activeStaff?.role === 'taker') {
        return o.orderTakerId === activeStaff.id;
      }

      return true;
    })
    .sort((a, b) => {
      const priority = { 'preparing': 1, 'received': 2, 'ready': 3 };
      const pA = priority[a.status as keyof typeof priority] || 99;
      const pB = priority[b.status as keyof typeof priority] || 99;
      
      if (pA !== pB) return pA - pB;
      return a.timestamp - b.timestamp;
    });

  const aggregatedItems = activeOrders
    .filter(o => o.status !== 'ready')
    .reduce((acc: Record<string, { name: string, quantity: number, unit: string }>, order) => {
      order.items.forEach(item => {
        if (!acc[item.id]) {
          acc[item.id] = { name: item.name, quantity: 0, unit: item.unit };
        }
        acc[item.id].quantity += item.quantity;
      });
      return acc;
    }, {});

  const summaryList = Object.values(aggregatedItems).sort((a: any, b: any) => b.quantity - a.quantity);

  const getStatusColor = (status: OrderStatus) => {
    switch (status) {
      case 'received': return 'bg-blue-500';
      case 'preparing': return 'bg-amber-500';
      case 'ready': return 'bg-emerald-500';
      default: return 'bg-gray-500';
    }
  };

  const getStatusLabel = (status: OrderStatus) => {
    switch (status) {
      case 'received': return 'New Order';
      case 'preparing': return 'Preparing';
      case 'ready': return 'Ready';
      default: return status;
    }
  };

  const getStatusProgress = (status: OrderStatus) => {
    switch (status) {
      case 'received': return 33;
      case 'preparing': return 66;
      case 'ready': return 100;
      default: return 0;
    }
  };

  const isKitchen = activeStaff?.role === 'kitchen';

  const stats = {
    new: orders.filter(o => o.status === 'received').length,
    preparing: orders.filter(o => o.status === 'preparing').length,
    ready: orders.filter(o => o.status === 'ready').length,
  };

  return (
    <div className="space-y-4 pb-20">
      {/* Kitchen Header & Stats */}
      <div className="bg-[var(--bg-card)] p-8 rounded-[48px] border border-white/5 shadow-2xl space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className={`p-4 rounded-2xl shadow-lg ${isKitchen ? 'bg-orange-600 text-white shadow-orange-600/20' : 'bg-blue-600 text-white shadow-blue-600/20'}`}>
              {isKitchen ? ICONS.ChefHat : ICONS.History}
            </div>
            <div>
              <h2 className="text-3xl font-black uppercase italic tracking-tighter text-white leading-none">
                {isKitchen ? 'Kitchen' : 'Order'} <span className={isKitchen ? 'text-orange-600' : 'text-blue-600'}>Monitor</span>
              </h2>
              <p className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest mt-1">
                {isKitchen ? 'Real-time production dashboard' : 'Track your active orders'}
              </p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {isKitchen && (
              <button 
                onClick={() => setShowSummary(!showSummary)}
                className={`flex items-center gap-2 px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all active:scale-95 ${
                  showSummary ? 'bg-orange-600 text-white border-orange-600 shadow-lg' : 'bg-white/5 text-orange-600 border-orange-600/20 hover:bg-white/10'
                }`}
              >
                {ICONS.Settings}
                {showSummary ? 'Hide Summary' : 'Show Summary'}
              </button>
            )}
            {isKitchen && (
              <button 
                onClick={() => setViewMode(viewMode === 'active' ? 'print' : 'active')}
                className={`flex items-center gap-2 px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest border transition-all active:scale-95 ${
                  viewMode === 'print' ? 'bg-emerald-600 text-white border-emerald-600 shadow-lg' : 'bg-white/5 text-emerald-600 border-emerald-600/20 hover:bg-white/10'
                }`}
              >
                {ICONS.Inventory}
                {viewMode === 'print' ? 'View Orders' : 'Print List'}
              </button>
            )}
            <div className="bg-black/40 px-5 py-2.5 rounded-2xl border border-white/5 text-center min-w-[80px]">
              <p className="text-[8px] font-black text-[var(--text-muted)] uppercase tracking-widest">Active</p>
              <p className="text-lg font-black text-white">{activeOrders.length}</p>
            </div>
          </div>
        </div>

        {isKitchen && showSummary && summaryList.length > 0 && (
          <motion.div 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-black/60 p-6 rounded-[32px] border border-orange-600/20 space-y-4 shadow-2xl"
          >
            <div className="flex items-center justify-between border-b border-white/5 pb-3">
              <div className="flex items-center gap-2">
                <div className="w-2 h-2 rounded-full bg-orange-600 animate-pulse" />
                <h4 className="text-[12px] font-black uppercase tracking-widest text-orange-600">Production Summary</h4>
              </div>
              <span className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest bg-white/5 px-3 py-1 rounded-full">{summaryList.length} Items Total</span>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
              {summaryList.map((item: any, idx) => (
                <div key={idx} className="bg-white/5 p-4 rounded-2xl flex items-center justify-between border border-white/5 hover:border-orange-600/30 transition-all">
                  <span className="text-[12px] font-black text-white/90 uppercase truncate pr-2">{item.name}</span>
                  <span className="bg-orange-600 text-white px-3 py-1.5 rounded-xl text-[12px] font-black min-w-[32px] text-center shadow-lg shadow-orange-600/20">
                    {item.unit === 'rs' ? 'Any' : item.quantity}
                  </span>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {isKitchen && !showSummary && (
          <div className="grid grid-cols-3 gap-3">
            <div className="bg-blue-600/10 border border-blue-600/20 p-4 rounded-[24px] text-center group hover:bg-blue-600/20 transition-all">
              <p className="text-[10px] font-black text-blue-500 uppercase tracking-widest">New</p>
              <p className="text-3xl font-black text-white group-hover:scale-110 transition-transform">{stats.new}</p>
            </div>
            <div className="bg-amber-600/10 border border-amber-600/20 p-4 rounded-[24px] text-center group hover:bg-amber-600/20 transition-all">
              <p className="text-[10px] font-black text-amber-500 uppercase tracking-widest">Cooking</p>
              <p className="text-3xl font-black text-white group-hover:scale-110 transition-transform">{stats.preparing}</p>
            </div>
            <div className="bg-emerald-600/10 border border-emerald-600/20 p-4 rounded-[24px] text-center group hover:bg-emerald-600/20 transition-all">
              <p className="text-[10px] font-black text-emerald-500 uppercase tracking-widest">Ready</p>
              <p className="text-3xl font-black text-white group-hover:scale-110 transition-transform">{stats.ready}</p>
            </div>
          </div>
        )}
      </div>

      {viewMode === 'active' && (
        <>
          <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-hide px-1">
            {(['all', 'received', 'preparing', 'ready'] as const).map(s => (
              <button
                key={s}
                onClick={() => setFilterStatus(s)}
                className={`px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all border whitespace-nowrap ${
                  filterStatus === s 
                    ? 'bg-orange-600 text-white border-orange-600 shadow-xl scale-105' 
                    : 'bg-white/5 text-[var(--text-muted)] border-white/5 hover:bg-white/10'
                }`}
              >
                {s === 'all' ? 'All Active' : getStatusLabel(s)}
              </button>
            ))}
          </div>

          <div className={`grid gap-4 px-1 ${isKitchen ? 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3' : 'grid-cols-1'}`}>
            <AnimatePresence mode="popLayout">
              {activeOrders.map(order => {
                const timeDiff = Date.now() - order.timestamp;
                const isUrgent = timeDiff > 15 * 60 * 1000 && order.status !== 'ready';

            return (
              <motion.div 
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                key={order.id}
                className={`bg-[var(--bg-card)] rounded-[32px] border p-5 space-y-4 shadow-2xl relative overflow-hidden flex flex-col h-full transition-all duration-500 ${
                  isUrgent ? 'border-red-600/50 ring-2 ring-red-600/20 bg-red-600/5' : 'border-[var(--border)]'
                } ${
                  order.status === 'received' ? 'ring-2 ring-blue-500 ring-offset-4 ring-offset-black' : ''
                } ${
                  order.status === 'ready' ? 'border-emerald-500/50 bg-emerald-500/5' : ''
                } ${order.isPrinted ? 'bg-emerald-600/5 border-emerald-600/30' : ''}`}
              >
                {/* Progress Bar */}
                <div className="absolute top-0 left-0 right-0 h-1 bg-white/5">
                  <motion.div 
                    initial={{ width: 0 }}
                    animate={{ width: `${getStatusProgress(order.status!)}%` }}
                    className={`h-full transition-all duration-1000 ${getStatusColor(order.status!)}`}
                  />
                </div>

                {/* Status Header */}
                <div className="flex justify-between items-start pt-1">
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-2">
                      <span className="text-2xl font-black text-orange-600 uppercase tracking-widest bg-orange-600/10 px-3 py-1 rounded-lg border border-orange-600/20">#{order.orderNumber || '??'}</span>
                      <span className={`px-2.5 py-1 rounded-xl text-[9px] font-black text-white uppercase tracking-widest shadow-lg ${getStatusColor(order.status!)}`}>
                        {getStatusLabel(order.status!)}
                      </span>
                      {order.tableNumber ? (
                        <span className="bg-orange-600/10 text-orange-600 px-2.5 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest border border-orange-600/20">
                          Table {order.tableNumber}
                        </span>
                      ) : (
                        <span className="bg-blue-600/10 text-blue-600 px-2.5 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest border border-blue-600/20">
                          Takeaway
                        </span>
                      )}
                      {order.isPrinted && (
                        <span className="bg-emerald-600 text-white px-2.5 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest flex items-center gap-1 shadow-lg shadow-emerald-600/20">
                          {ICONS.CheckCircle} PRINTED
                        </span>
                      )}
                    </div>
                    <h3 className="text-2xl font-black text-white uppercase italic tracking-tighter leading-none">
                      {order.customerName}
                    </h3>
                  </div>
                  <div className="text-right">
                    <p className="text-[10px] font-black text-[var(--text-muted)] uppercase">
                      {new Date(order.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </p>
                    <TimeElapsed 
                      timestamp={order.timestamp} 
                      statusTimestamps={order.statusTimestamps}
                      currentStatus={order.status}
                      className={`text-[10px] font-black uppercase block mt-1 ${isUrgent ? 'text-red-500 animate-pulse' : 'text-orange-600'}`}
                    />
                  </div>
                </div>

                {/* Items List / Kitchen Tickets */}
                <div className="flex-1 space-y-3 bg-black/40 p-5 rounded-[28px] border border-white/5 shadow-inner overflow-y-auto">
                  {order.kitchenTickets && order.kitchenTickets.length > 0 ? (
                    <div className="space-y-4">
                      {order.kitchenTickets.slice(-1).map(ticket => (
                        <div key={ticket.id} className="space-y-2 bg-white/5 p-4 rounded-2xl border border-white/10 relative">
                          {order.kitchenTickets!.length > 1 && (
                            <div className="absolute -top-3 left-4 bg-orange-600 font-black text-[9px] uppercase tracking-widest px-3 py-1 rounded-xl text-white shadow-lg border border-orange-500/50">
                              Ticket {ticket.round}
                            </div>
                          )}
                          <div className={order.kitchenTickets!.length > 1 ? "pt-2 space-y-2" : "space-y-2"}>
                            {ticket.items.map((item, idx) => (
                              <div key={idx} className="flex justify-between items-center border-b border-white/5 last:border-0 pb-2.5 last:pb-0 pt-2.5 first:pt-0">
                                <div className="flex items-center gap-4">
                                  <span className="w-9 h-9 bg-orange-600 text-white rounded-2xl flex items-center justify-center text-base font-black shadow-xl ring-4 ring-orange-600/10">
                                    {item.quantity > 0 && order.kitchenTickets!.length > 1 ? `+${item.quantity}` : item.quantity}
                                  </span>
                                  <span className="text-lg font-black text-white/90 uppercase tracking-tight italic leading-tight">{item.name}</span>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {order.items.map((item, idx) => (
                        <div key={idx} className="flex justify-between items-center border-b border-white/5 last:border-0 pb-2.5 last:pb-0 pt-2.5 first:pt-0">
                          <div className="flex items-center gap-4">
                            <span className="w-9 h-9 bg-orange-600 text-white rounded-2xl flex items-center justify-center text-base font-black shadow-xl ring-4 ring-orange-600/10">
                              {item.quantity}
                            </span>
                            <span className="text-lg font-black text-white/90 uppercase tracking-tight italic leading-tight">{item.name}</span>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                  {order.kitchenNotes && (
                    <div className="mt-3 pt-3 border-t border-white/5">
                      <div className="flex items-center gap-2 mb-1.5">
                        <span className="text-amber-500 scale-75">{ICONS.Settings}</span>
                        <p className="text-[10px] font-black text-amber-500 uppercase tracking-widest">Special Instructions</p>
                      </div>
                      <p className="text-sm text-white/80 italic leading-snug bg-amber-500/5 p-3 rounded-2xl border border-amber-500/10">
                        {order.kitchenNotes}
                      </p>
                    </div>
                  )}
                </div>

                {/* Action Buttons */}
                <div className="flex gap-2 pt-2">
                  {isAdmin && (
                    <>
                      <button 
                        onClick={() => triggerConfirm({
                          title: "Cancel Order?",
                          message: "Kya aap waqai is order ko cancel karna chahte hain?",
                          onConfirm: () => onUpdateStatus(order, 'cancelled')
                        })}
                        className="p-4 bg-red-600/10 text-red-500 rounded-2xl active:scale-95 transition-all hover:bg-red-600/20"
                        title="Cancel Order"
                      >
                        {ICONS.Trash2}
                      </button>
                      
                      <button 
                        onClick={() => onEditOrder(order)}
                        className="p-4 bg-blue-600/10 text-blue-500 rounded-2xl active:scale-95 transition-all hover:bg-blue-600/20"
                        title="Edit Order"
                      >
                        {ICONS.Settings}
                      </button>
                    </>
                  )}

                  {order.status === 'received' && (
                    <button 
                      onClick={() => onUpdateStatus(order, 'preparing')}
                      className="flex-1 py-5 bg-indigo-600 text-white rounded-2xl font-black uppercase text-[12px] tracking-widest active:scale-95 transition-all shadow-xl shadow-indigo-600/20 flex items-center justify-center gap-3"
                    >
                      {ICONS.CheckCircle}
                      Receive Order
                    </button>
                  )}
                  {order.status === 'preparing' && (
                    <button 
                      onClick={() => onUpdateStatus(order, 'ready')}
                      className="flex-1 py-5 bg-emerald-600 text-white rounded-2xl font-black uppercase text-[12px] tracking-widest active:scale-95 transition-all shadow-xl shadow-emerald-600/20 flex items-center justify-center gap-3"
                    >
                      {ICONS.Utensils}
                      Mark Ready
                    </button>
                  )}
                  {order.status === 'ready' && (
                    <div className="flex-1 py-5 bg-emerald-600/20 text-emerald-500 rounded-2xl font-black uppercase text-[12px] tracking-widest flex items-center justify-center gap-3 border-2 border-emerald-500/30 shadow-lg shadow-emerald-500/10 animate-pulse">
                      <div className="w-3 h-3 rounded-full bg-emerald-500 shadow-[0_0_15px_rgba(16,185,129,0.8)]" />
                      ORDER READY
                    </div>
                  )}
                  {isKitchen && (
                    <button 
                      onClick={() => handlePrintOrder(order)}
                      className="p-4 bg-emerald-600/10 text-emerald-600 rounded-2xl active:scale-95 transition-all hover:bg-emerald-600/20"
                      title="Print Order"
                    >
                      {ICONS.Inventory}
                    </button>
                  )}
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>
      </>
      )}

      {viewMode === 'print' && (
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="space-y-4"
        >
          <div className="bg-[var(--bg-card)] p-6 rounded-[32px] border border-emerald-600/20">
            <h3 className="text-xl font-black uppercase italic tracking-tighter text-emerald-600">Print <span className="text-white">Queue</span></h3>
            <p className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest mt-1">Pending kitchen prints</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {activeOrders.map(order => (
              <div key={order.id} className={`bg-[var(--bg-card)] p-6 rounded-[32px] border transition-all flex justify-between items-center shadow-xl ${order.isPrinted ? 'border-emerald-600/50 bg-emerald-600/5 opacity-80' : 'border-white/5 border-l-4 border-l-emerald-600'}`}>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-lg font-black text-white italic tracking-tighter uppercase leading-none truncate max-w-[120px]">{order.customerName}</span>
                    <span className="text-xs font-black text-emerald-500">#{order.orderNumber}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <p className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest">Table: {order.tableNumber || 'Takeaway'}</p>
                    {order.isPrinted && <span className="text-[9px] font-black text-emerald-500 uppercase flex items-center gap-1">{ICONS.CheckCircle} PRINTED</span>}
                  </div>
                </div>

                <button 
                  onClick={() => handlePrintOrder(order)}
                  className={`flex items-center gap-2 px-6 py-4 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all active:scale-95 shadow-xl ${
                    order.isPrinted 
                      ? 'bg-white/5 text-emerald-600 border border-emerald-600/20' 
                      : 'bg-emerald-600 text-white shadow-emerald-600/20'
                  }`}
                >
                  {ICONS.Inventory}
                  {order.isPrinted ? 'Print Again' : 'Print Token'}
                </button>
              </div>
            ))}
          </div>
        </motion.div>
      )}
    </div>
  );
};

export default LiveOrdersView;
